### ISSUE TITLE
Bug with wpsight_listings shortcode attributes

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#34] opened 2016-08-01 22:25 UTC
It seems like the shortcode ignore URL Parameters to order listings.

Eg. by using [wpsight_listings orderby="price" order="ASC"] the original order works fine, but if the user re-orders them live from the dropdown, the results will stay the same.

The shortcode probably needs to first check if URL Parameters are available and only apply the shortcode attributes if there are no URL Parameters.

**Comment by simonrimkus** [comment] 2016-08-02 08:51
Closing as a duplicate of #25

**Closed by simonrimkus** 2016-08-02 08:51 UTC
